[[pages]]
path = "ë©”ì¸.py"
name = "ë©”ì¸"
icon = "ğŸŒ²"

[[pages]]
path = "ì‚¬ìš©ìì…ë ¥.py"
name = "ì‚¬ìš©ìì…ë ¥"
icon = "ğŸ“"

[[pages]]
path = "ì‹ë¬¼.py"
name = "ê½ƒê°€ë£¨ ì•ŒëŸ¬ì§€ì™€ ì‹ë¬¼ ì •ë³´"
icon = "ğŸŒ¿"

[[pages]]
path = "ì ˆì§€ë™ë¬¼.py"
name = "ì ˆì§€ë™ë¬¼"
icon = "ğŸ•·ï¸"

[[pages]]
path = "ë³‘ì›.py"
name = "ë³‘ì›"
icon = "ğŸ¥"
